### ISSUE TITLE
Halloween Update

### ISSUE THREAD

**Issue by sanjaykdragon** [flatlinee/flathud#11]
There is no spells showing in the Halloween Update. I tried config'ing, didnt work.

**Comment by robobenklein** [comment]
They appear to work for me,

Could you give more information, maybe screenshots of what the HUD looks like when you have picked up a spell and when you have not?
What screen resolution & OS are you on? Have you completely deleted the flathud custom folder and re-copied? Are you perhaps using any other customizations?

**Comment by sanjaykdragon** [comment]
I'm using flathudred from huds.tf. Will try downloading flathudred from here, if that doesnt work will try flathudblue.

OS: Windows 10
Res: 1920x1080
16:9

**Comment by flatlinee** [comment]
There's no difference between the files in flathudred and the files in flathudblue for spell selection.
