### ISSUE TITLE
net_graph obscures item inspect panel

### ISSUE THREAD

**Issue by mon** [flatlinee/flathud#5]
Issue is what it says on the tin - perhaps move the inspect panel up half way instead of bottom right?

**Comment by flatlinee** [comment]
The net graph has more than 1 position, try messing with them.  The inspect panels are wonky because their size depends wholly on the description of the item's size.  Also, they are locked where they are in spectator mode, so I can't do that.

**Comment by mon** [comment]
Them being locked seems to be an issue with Gun Mettle, or the old default was centered. I'll play with different graph locations.
