### ISSUE TITLE
Health background

### ISSUE THREAD

**Issue by Avaray** [flatlinee/flathud#7]
Hey, I have one problem from long time (in older and newest versions of HUD)
Sometimes after spawn there is Yellow health background, sometimes Red and sometimes Green (without any overhal).
And that color is there until I will get less than 100 HP (as I remember).

**Comment by Avaray** [comment]
Also sometimes ammo have red background on start
http://i.imgur.com/PDrl6Jd.jpg

**Comment by Tsunamical** [comment]
Didn't realize team names (With g, q, y, p or j) clip out of the team colored box until now. Might want to decrease the font size or make the box bigger on top of that.

**Comment by robobenklein** [comment]
@Tsunamical I thought it looked fine to have the letters slightly overlap the border, IMHO.

I can concur that sometimes the colors intended for low ammo/health notification are sometimes present when they should not be.

**Comment by flatlinee** [comment]
that's a TF2 bug that happens with hudanimations (this is the same bug that sometimes had your health colored green or yellow in older versions).  it is unfixable until you change the state of your health (either to buff or normal or hurt)
