### ISSUE TITLE
Item Descriptions and Names

### ISSUE THREAD

**Issue by robobenklein** [flatlinee/flathud#8]
Items do not have proper tags apparently,
![problems](https://cloud.githubusercontent.com/assets/5423266/11611496/e8ae9f70-9b9e-11e5-886a-71d7574569cf.png)

Reinstall didn't help.
Not all items are affected, only Halloween and Collection items for me.

**Comment by flatlinee** [comment]
remove tf_english from your /resource directory

it shouldn't be there at all so i have no idea why people still ahve it unless you're manually replacing files
